### ISSUE TITLE
Fails to build with es6 modules

### ISSUE THREAD

**Issue by joprice** [rhysforyou/bs-enzyme#14]
When setting `package-specs.module` to "es6", I get the error `TypeError: EnzymeAdapterReact is not a constructor`.

**Comment by rhysforyou** [comment]
Hmm i'll take a look

**Comment by joprice** [comment]
Seems like some typescript users have had this issue as well. https://github.com/airbnb/enzyme/issues/1284

**Comment by rhysforyou** [comment]
I started looking at this, but Jest really hates dealing with ES Modules so I've had some trouble getting the test suite running on ES6 builds.

**Comment by rhysforyou** [comment]
Okay looking into this, the [BuckleScript docs](https://bucklescript.github.io/docs/en/import-export#import-a-default-value) are actually pretty clear on how to handle this situation. I had to change this:

```reason
[@bs.module] [@bs.new] external react_16_adapter : unit => adapter = "enzyme-adapter-react-16";
```

to this:

```reason
[@bs.module "enzyme-adapter-react-16"] [@bs.new] external react_16_adapter : unit => adapter = "default";
```

and that appears to have resolved everything.

I'm leaving this PR open for now, but could you test the latest release and see if that fixes the issue?

**Comment by rhysforyou** [comment]
Okay this is a known issue in BuckleScript, see https://github.com/BuckleScript/bucklescript/issues/2113

I'm keeping this PR open until that's fixed upstream.

**Comment by erykpiast** [comment]
What would be the issue if we changed typings to something like this?

```
[@bs.module "enzyme-adapter-react-16"] [@bs.new] external react_16_adapter : unit => adapter = "default";
```
