### ISSUE TITLE
Add support for type selectors

### ISSUE THREAD

**Issue by lukashambsch** [rhysforyou/bs-enzyme#15]
When trying to use the `input[type=checkbox]` selector, I get a `Failed to parse selector: input[type=checkbox]` error.

**Comment by rhysforyou** [comment]
Hmm my hunch is that this is an underlying issue with Enzyme, but I'll take a look at it

**Comment by rhysforyou** [comment]
Yeah it looks like it's generating the correct code for this, the following code:

```reason
wrapper |> Enzyme.Shallow.find("input[type=checkbox]")
```

Is correctly transpiled to this:

```js
wrapper.find("input[type=checkbox]")
```

I'd open an issue on the core Enzyme repo for this.

**Comment by lukashambsch** [comment]
Will do, thank!

**Comment by lukashambsch** [comment]
In case anyone else runs into the issue. My selector was wrong. I didn't have quotes around checkbox.

Both versions work in the Chrome console, but only `input[type="checkbox"]` works w/ enzyme.

**Comment by ma-xin-developer** [comment]
Please use input[type="checkbox"] but not input[type=checkbox].

@see: https://enzymejs.github.io/enzyme/docs/api/selector.html#1-a-valid-css-selector
